'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Location

    '''<summary>
    '''row_comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row_comment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ll_ok1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_ok1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ll_ok2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_ok2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txt_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_location As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_search As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_save As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''grd_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_location As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_location_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_location_id As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_choice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_choice As Global.System.Web.UI.WebControls.Label
End Class
