'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class User_View

    '''<summary>
    '''lbl_employe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_employe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ll_close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_close As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl_firstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_firstname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_lastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lastname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_username As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_password As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ll_reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_reset As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl_role control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_role As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ll_modify_role control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_modify_role As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ll_save_role control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_save_role As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ll_cancel_role control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_cancel_role As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ll_modify_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_modify_status As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ll_save_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_save_status As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ll_cancel_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_cancel_status As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''row_comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row_comments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_comments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_comments As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cbx_administration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_administration As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbx_rrhh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_rrhh As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbx_finances control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_finances As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbx_settings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_settings As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbx_client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_client As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbx_proforma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_proforma As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbx_reservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_reservation As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbx_invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_invoice As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbx_report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_report As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''row_comment2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row_comment2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grd_employe_comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_employe_comments As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_employe_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_employe_id As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grd_user control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_user As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grd_autjorization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_autjorization As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grd_role control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_role As Global.System.Web.UI.WebControls.GridView
End Class
