'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Proforma

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbl_id_proforma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_id_proforma As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ll_close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_close As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl_comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_time As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_home control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_home As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_pickup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_pickup As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_dropoff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_dropoff As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ll_ok_itinerary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_ok_itinerary As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ll_add_new control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_add_new As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents table1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''th_row0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents th_row0 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''lbl_origin0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_origin0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_destination0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_destination0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_time0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_time0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_distance0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_distance0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ll_erase0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_erase0 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''th_row1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents th_row1 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''lbl_origin1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_origin1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_destination1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_destination1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_time1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_time1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_distance1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_distance1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ll_erase1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_erase1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''th_row2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents th_row2 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''lbl_origin2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_origin2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_destination2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_destination2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_time2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_time2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_distance2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_distance2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ll_erase2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_erase2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''th_row3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents th_row3 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''lbl_origin3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_origin3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_destination3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_destination3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_time3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_time3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_distance3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_distance3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ll_erase3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_erase3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''th_row4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents th_row4 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''lbl_origin4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_origin4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_destination4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_destination4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_time4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_time4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_distance4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_distance4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ll_erase4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ll_erase4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl_rowcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_rowcount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_total_time_deadmile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_total_time_deadmile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_total_distance_deadmile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_total_distance_deadmile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_total_time_loadedmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_total_time_loadedmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_total_distance_loaded_miles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_total_distance_loaded_miles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_distance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_distance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_waittime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_waittime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_attendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_attendant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_rental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_rental As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_bariatric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bariatric As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_stairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_stairs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_rush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_rush As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_afterhours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_afterhours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_intake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_intake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grd_company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_company As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_company_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_flat_rate_option control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_flat_rate_option As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_selection0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_selection0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbx_deadmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_deadmiles As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_deadmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_deadmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbx_loadedmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_loadedmiles As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_loadedmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_loadedmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender2 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbx_leg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_leg As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_leg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_leg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender3 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbx_waittime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_waittime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_waittime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_waittime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender4 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbx_attendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_attendant As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_attendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_attendant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender5 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbx_rental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_rental As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_rental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_rental As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender6 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbx_bariatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_bariatic As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_bariatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_bariatic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender7 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbx_stairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_stairs As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_stairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_stairs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender8 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbx_rush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_rush As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_rush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_rush As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender9 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbx_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_other As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender10 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''cbx_afterhours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_afterhours As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_qte_afterhours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_qte_afterhours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FilteredTextBoxExtender11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender11 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''rbtn_selection1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtn_selection1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lbl_selection1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_selection1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_lrate_deadmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_deadmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_deadmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_deadmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lrate_loadedmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_loadedmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_loadedmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_loadedmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lrate_leg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_leg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_leg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_leg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lrate_waittime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_waittime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_waittime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_waittime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lrate_attendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_attendant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_attendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_attendant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lrate_rental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_rental As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_rental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_rental As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lrate_bariatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_bariatic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_bariatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_bariatic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lrate_stairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_stairs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_stairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_stairs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lrate_rush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_rush As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_rush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_rush As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lrate_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lrate_afterhours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lrate_afterhours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_lrate_afterhours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_lrate_afterhours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbtn_selection2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtn_selection2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lbl_selection2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_selection2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_mrate_deadmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_deadmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_deadmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_deadmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mrate_loadedmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_loadedmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_loadedmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_loadedmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mrate_leg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_leg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_leg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_leg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mrate_waittime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_waittime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_waittime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_waittime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mrate_attendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_attendant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_attendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_attendant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mrate_rental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_rental As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_rental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_rental As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mrate_bariatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_bariatic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_bariatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_bariatic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mrate_stairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_stairs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_stairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_stairs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mrate_rush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_rush As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_rush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_rush As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mrate_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mrate_afterhours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mrate_afterhours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_mrate_afterhours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_mrate_afterhours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbtn_selection3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtn_selection3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lbl_selection3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_selection3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_hrate_deadmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_deadmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_deadmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_deadmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_hrate_loadedmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_loadedmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_loadedmiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_loadedmiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_hrate_leg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_leg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_leg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_leg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_hrate_waittime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_waittime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_waittime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_waittime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_hrate_attendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_attendant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_attendant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_attendant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_hrate_rental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_rental As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_rental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_rental As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_hrate_bariatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_bariatic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_bariatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_bariatic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_hrate_stairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_stairs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_stairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_stairs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_hrate_rush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_rush As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_rush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_rush As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_hrate_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_hrate_afterhours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hrate_afterhours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tot_hrate_afterhours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tot_hrate_afterhours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_calculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_calculate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_total_lrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_total_lrate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_cancel_lrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cancel_lrate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_total_mrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_total_mrate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_cancel_mrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cancel_mrate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_total_hrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_total_hrate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_cancel_hrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cancel_hrate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_reservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_reservation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grd_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_location As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grd_rates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_rates As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grd_proforma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_proforma As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grd_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_time As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_company_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_id As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_transport_lrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_transport_lrate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_transport_mrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_transport_mrate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_transport_hrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_transport_hrate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_service_fee_lrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_service_fee_lrate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_service_fee_mrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_service_fee_mrate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_service_fee_hrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_service_fee_hrate As Global.System.Web.UI.WebControls.Label
End Class
